version: "3.8"

volumes:
  data:

services:
  pg_database:
    container_name: database_app
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    container_name: api_app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - pg_database
    command: sh -c "dockerize -wait tcp://postgres:5432 -timeout 300s -wait-retry-interval 30s && echo 'Postgres is ready'"
